version: 2

project_name: splitdns

before:
  hooks:
    - go mod tidy

builds:
  - id: splitdns
    main: .
    binary: splitdns
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/soulteary/splitdns/cmd.version={{.Version}}
      - -X github.com/soulteary/splitdns/cmd.commit={{.Commit}}
      - -X github.com/soulteary/splitdns/cmd.date={{.Date}}

archives:
  - id: splitdns
    formats: [tar.gz]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - README.zh-CN.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

release:
  draft: false
